"""プロファイルカタログから docs/hardware-matrix.md（日本語）と
docs/hardware-matrix_en.md（英語）を生成する。

公開する表とツールが実際に選択するプロファイルが食い違わないよう、対応表は手作業で
管理せず生成する。プロファイルがないセルは「未検証」と表示し、隣接セルから補間しない。
"""

from __future__ import annotations

from .select import confidence_key

VRAM_TIERS = (8, 12, 16, 24)
PLATFORM_LABEL = {"linux": "Linux", "windows-wsl2": "Windows + WSL2"}
MATRIX_PATHS = {"ja": "hardware-matrix.md", "en": "hardware-matrix_en.md"}

HEADER_JA = """<!-- Generated by `narration-video-gen matrix --write`. Do not edit by hand. -->
# ハードウェア対応表

**日本語** | [English](hardware-matrix_en.md)

各セルは`profiles/`の構成と、その検証状況を示します。構成がないセルは「未検証」です。
ラベルの意味は[検証結果](evidence.md)を参照してください。

`narration-video-gen plan`または`select`を実行すると、このマシンに合う構成が選ばれます。
12 GiB以下の構成はQ4_K_Sモデルを使います（[低VRAM向けモデル選択](low-vram-model-policy.md)）。
"""

HEADER_EN = """<!-- Generated by `narration-video-gen matrix --write`. Do not edit by hand. -->
# Hardware matrix

[日本語](hardware-matrix.md) | **English**

Each cell shows a configuration from `profiles/` and how far it was verified.
Cells without a configuration read "not verified". See
[verification results](evidence_en.md) for what the labels mean.

`narration-video-gen plan` or `select` picks the configuration that fits your
machine. Configurations for 12 GiB and below use Q4_K_S models (see
[low-VRAM model selection](low-vram-model-policy_en.md)).
"""

TEXT = {
    "ja": {
        "header": HEADER_JA,
        "duration": {"full": "フル長", "short": "短尺", "gate": "gate"},
        "evidence": {"physical": "物理GPU", "capacity-simulated": "容量シミュレーション"},
        "visual": {"passed": "目視確認済み", "failed": "不合格", "pending": "未確認"},
        "separator": "、",
        "unverified": "未検証",
        "short_oom": "短尺でメモリ不足（Q4_K_S）",
        "planned": "未検証（Q4_K_S候補）",
        "inferred": "未検証（Wan 2.2の結果からの推定・Q4_K_S候補）",
        "resumed": "、途中で再開",
        "not_recommended": "**非推奨** -- ",
        "minutes": "、約%d分",
        "profiles": "プロファイル一覧",
        "columns": "| プロファイル | プラットフォーム | 解像度 | VRAM | ステータス |",
    },
    "en": {
        "header": HEADER_EN,
        "duration": {"full": "full length", "short": "short", "gate": "gate"},
        "evidence": {"physical": "physical GPU", "capacity-simulated": "capacity-simulated"},
        "visual": {"passed": "reviewed", "failed": "rejected", "pending": "not reviewed"},
        "separator": ", ",
        "unverified": "not verified",
        "short_oom": "out of memory in short test (Q4_K_S)",
        "planned": "not verified (Q4_K_S candidate)",
        "inferred": "not verified (estimated from Wan 2.2, Q4_K_S candidate)",
        "resumed": ", resumed once",
        "not_recommended": "**not recommended** -- ",
        "minutes": ", about %d min",
        "profiles": "Profiles",
        "columns": "| Profile | Platform | Resolution | VRAM | Status |",
    },
}


def render_matrix(catalog, language="ja"):
    text = TEXT[language]
    lines = [text["header"]]
    grouped = _group(catalog)

    for platform in ("linux", "windows-wsl2"):
        for family in _families(catalog):
            key = (platform, family)
            if key not in grouped:
                continue
            lines.append("\n## %s / %s\n" % (PLATFORM_LABEL[platform], family))
            lines.append("| VRAM | 480p | 720p |")
            lines.append("|---:|---|---|")
            for tier in VRAM_TIERS:
                cells = []
                for resolution in ("480p", "720p"):
                    profile = grouped[key].get((tier, resolution))
                    cells.append(_cell(profile, text) if profile else text["unverified"])
                lines.append("| %d GiB | %s | %s |" % (tier, cells[0], cells[1]))

    lines.append("\n## %s\n" % text["profiles"])
    lines.append(text["columns"])
    lines.append("|---|---|---|---:|---|")
    for profile in catalog.sorted_profiles():
        recipe = catalog.recipe_for(profile)
        lines.append("| `%s` | %s | %dp | %s GiB | %s |" % (
            profile["id"], PLATFORM_LABEL[profile["platform"]],
            recipe["resolution"][1], profile["requires"].get("gpu_vram_gib_min", "?"),
            profile["status"],
        ))
    lines.append("")
    return "\n".join(lines)


def _families(catalog):
    seen = []
    for recipe in catalog.recipes.values():
        if recipe.get("kind", "video") != "video":
            continue
        family = recipe["model_family"]
        if family not in seen:
            seen.append(family)
    return sorted(seen)


def _group(catalog):
    grouped = {}
    for profile in catalog.sorted_profiles():
        recipe = catalog.recipe_for(profile)
        key = (profile["platform"], recipe["model_family"])
        tier = profile["requires"].get("gpu_vram_gib_min")
        resolution = "%dp" % recipe["resolution"][1]
        cells = grouped.setdefault(key, {})
        cell = (tier, resolution)
        previous = cells.get(cell)
        # Several profiles can describe one cell (for example a retained tiled
        # fallback and a native profile). Show the same highest-confidence one
        # that selection would favour, rather than whichever filename sorts last.
        if (previous is None
                or confidence_key(profile, recipe) > confidence_key(
                    previous, catalog.recipe_for(previous))):
            cells[cell] = profile
    return grouped


def _cell(profile, text=TEXT["ja"]):
    ev = profile["evidence"]
    parts = [
        text["duration"].get(ev["duration_class"], ev["duration_class"]),
        text["evidence"].get(ev["gpu_evidence"], ev["gpu_evidence"]),
        text["visual"].get(ev["visual_review"], ev["visual_review"]),
    ]
    cell = text["separator"].join(parts)
    if profile.get("qualification_state") == "short-oom":
        cell = text["short_oom"]
    elif profile.get("qualification_state") == "planned":
        cell = text["planned"]
    elif profile.get("qualification_state") == "inferred":
        cell = text["inferred"]
    if ev.get("execution_mode") == "staged-resumed-after-wsl-restart":
        cell += text["resumed"]
    requires = profile.get("requires") or {}
    if requires.get("physical_ram_gib_min") == 24 and requires.get("gpu_vram_gib_min", 99) <= 12:
        cell += "<br>DRAM24 / WSL%s / swap%s GiB" % (
            requires.get("host_ram_gib_min"), requires.get("swap_gib_min"))
    if profile["status"] == "not-recommended":
        cell = text["not_recommended"] + cell
    settings = profile.get("settings") or {}
    if "blocks_to_swap" in settings:
        cell += "<br>`blocks_to_swap=%s`" % settings["blocks_to_swap"]
    reference = (profile.get("timing") or {}).get("reference") or {}
    minutes = (float(reference["wall_clock_seconds"]) / 60.0
               if reference.get("wall_clock_seconds") is not None
               else ev.get("wall_clock_minutes"))
    if minutes:
        cell += text["minutes"] % round(minutes)
    return "%s<br>`%s`" % (cell, profile["id"])
